:host := "http://localhost:4242"

# root
GET :host

# test 
GET :host/tp/a/b?z=1

# test2
GET :host/test2?word=tmp1&tmp=tmp2

# json test
GET :host/jsontest

# add user
POST :host/user/add
Content-Type: application/json
{
    "auth": {
        "id": "test-id37",
        "email": "test-email@mail.com37",
        "name": "test-name",
        "nickname": "test-nickname",
        "password": "test-password",
    }
}

# login user
POST :host/user/login
Content-Type: application/json
{
    "auth": {
        "id": "test-id",
        "password": "test-password",
    }
}

# logout user
POST :host/user/logout
Content-Type: application/json
{
    "auth": {
        "id": "test-id",
        "password": "test-password",
    }
}

# logout user
POST :host/user/writepost
Content-Type: application/json
{
    "id": "1",
    "title": "new 11",
    "content": "new 22",
}

# get post 
GET :host/post?postid=15

# delete post
GET :host/post/delete?postid=26

# list
GET :host/


# list page 1
GET :host/?page=1


# list page 2
GET :host/?page=2

# Search
GET :host/search/title?keywords=33&keywords=test&page=1