:host := "http://localhost:4242"

# root
GET :host

# test 
GET :host/test2?word=tmp1&tmp=tmp2

# json test
GET :host/jsontest

# add user
POST :host/add-user
Content-Type: application/json
{
    "auth": {
        "id": "test-id2",
        "name": "test-name",
        "nickname": "test-nickname",
        "email": "test-email@mail.com2",
        "password": "test-password",
    }
}

# login user
POST :host/user/login
Content-Type: application/json
{
    "auth": {
        "id": "test-id",
        "password": "test-password",
    }
}

# logout user
POST :host/user/logout
Content-Type: application/json
{
    "auth": {
        "id": "test-id",
        "password": "test-password",
    }
}


# list
GET :host/


# list page 1
GET :host/?page=1


# list page 2
GET :host/?page=2