:host := "http://localhost:4242"

# root
GET :host

# test 
GET :host/test2?word=tmp1&tmp=tmp2

# add user
POST :host/add-user
Content-Type: application/json
{
    "auth": {
        "id": "test-id",
        "pw": "test-password",
    }
}